create table atbats (
	abid int not null auto_increment,
	gid varchar(30) not null,
	bid int not null,
	pid int not null,
	abno smallint not null,
	des varchar(255),
	balls smallint not null,
	strikes smallint not null,
	outs smallint not null,
	event varchar(255) not null,
	b_stand varchar(1) not null,
	p_throws varchar(1) not null,
	home_runs smallint not null,
	away_runs smallint not null,
	risp smallint not null,
 	runner_first smallint not null,
	runner_second smallint not null,
	runner_third smallint not null,
	rbi smallint not null,
	bases_advanced smallint not null,
	outs_caused smallint not null,
	foreign key(gid) references games(gid),
	foreign key(bid) references players(pid),
	foreign key(pid) references players(pid),
	primary key(abid)
)
