create table atbats (
	abid varchar(64) not null,
	game_date date not null,
	gid varchar(30) not null,
	bid int not null,
	pid int not null,
	abno smallint not null,
	des varchar(550),
	balls smallint not null,
	strikes smallint not null,
	outs smallint not null,
	event varchar(255) not null,
	home_runs smallint not null,
	away_runs smallint not null,
	risp smallint not null,
 	runner_first smallint not null,
	runner_second smallint not null,
	runner_third smallint not null,
	rbi smallint not null,
	foreign key(gid) references games(gid),
	foreign key(bid) references players(pid),
	foreign key(pid) references players(pid),
	primary key(abid)
)
